---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: fs1name
  namespace: demo
  annotations:
    flux.weave.works/tag.chart-image: glob:0.0.*
    flux.weave.works/automated: 'true'
spec:
  releaseName: fs1name
  chart:
    git: ssh://git@github.com/alexmelkor/flux-get-started.git
    ref: master
    path: charts/basic-chart
  values:
    tests:
      enabled: "true"
    image:
      repository: registry.battery-park.conductor.com/first-demo-service
      tag: 0.0.5
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
    serviceType: ClusterIP
