---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:*
spec:
  releaseName: jenkins
  chart:
    git: git@github.com:helm/charts.git
    ref: master
    path: stable/jenkins
  values:
    serviceType: NodePort
